feat: added make setup target (#359)

diff --git a/{{cookiecutter.project_slug}}/Makefile b/{{cookiecutter.project_slug}}/Makefile
--- a/{{cookiecutter.project_slug}}/Makefile
+++ b/{{cookiecutter.project_slug}}/Makefile
@@ -3,6 +3,15 @@ KUBECTL_EXEC_BACKEND = kubectl exec -it $$(kubectl get pods -l app=backend -o js
 KUBECTL_EXEC_FRONTEND = kubectl exec -it $$(kubectl get pods -l app=frontend -o jsonpath="{.items[0].metadata.name}") -- bash
 {% endif %}
 
+# colors
+BLUE:=$(shell echo "\033[0;36m")
+GREEN:=$(shell echo "\033[0;32m")
+YELLOW:=$(shell echo "\033[0;33m")
+RED:=$(shell echo "\033[0;31m")
+END:=$(shell echo "\033[0m")
+
+PROJECT_SLUG:="{{ cookiecutter.project_slug }}"
+
 ## Release/Deployment Targets
 
 .PHONY: ci
@@ -55,6 +64,35 @@ test: backend-test  ## Run all tests
 backend/requirements/local.txt: compile
 backend/requirements/production.txt: compile
 backend/requirements/tests.txt: compile
+
+setup:
+	@echo " $(YELLOW)⛭$(END) Checking if the setup is correct and all prerequisites are installed..."
+	@MISSING=""; \
+	for exec in $(PREREQUISITE_COMMANDS); do \
+		if ! which $$exec > /dev/null 2>&1; then \
+			MISSING="$$MISSING $$exec"; \
+		fi; \
+	done; \
+	if [ -n "$$MISSING" ]; then \
+		echo " $(RED)❌$(END)Missing executables:$$MISSING. These must be installed by you to continue"; \
+		false; \
+	else \
+		echo " $(GREEN)✔️$(END) All prerequisites are installed."; \
+	fi
+	@CURRENT_CONTEXT="$$(kubectl config current-context 2>&1)"; \
+	if [ "$$CURRENT_CONTEXT" = "kind-$(PROJECT_SLUG)" ]; then \
+		echo " $(GREEN)✔️$(END) The kubectl context is correctly set to kind-$(PROJECT_SLUG). Run 'tilt up' to start your cluster!"; \
+	else \
+		echo " $(YELLOW)⛭$(END) Current kubectl context is not 'kind-$(PROJECT_SLUG)'. Switching context now..."; \
+		if [ -z "$$(kubectl config get-contexts -o name | grep -w 'kind-$(PROJECT_SLUG)$$')" ]; then \
+			echo " $(YELLOW)⛭$(END) No context found for kind-$(PROJECT_SLUG). Creating one. Please wait, this may take a couple of minutes on a slower machine..."; \
+			kind create cluster --name $(PROJECT_SLUG) 1>/dev/null 2>/tmp/scaf_error.log; \
+			echo " $(GREEN)✔️$(END) kind-$(PROJECT_SLUG) cluster and context created."; \
+			echo " $(BLUE)🗣️ Remember, you can safely run \"make setup\" any time to switch between Scaf projects.$(END)"; \
+		fi; \
+		kubectl config use-context kind-$(PROJECT_SLUG) 1>/dev/null 2>/tmp/scaf_error.log; \
+		echo " $(GREEN)✔️$(END) Context switched to kind-$(PROJECT_SLUG). Run 'tilt up' to start your cluster! "; \
+	fi
 
 outdated: ## Show all the outdated packages with their latest versions in the container
 	$(KUBECTL_EXEC_BACKEND) -c "pip list --outdated"
