feat: Move tasks to individual templates

diff --git a/scaf b/scaf
--- a/scaf
+++ b/scaf
@@ -138,69 +138,14 @@ if [ -z "$REPO_URL" ]; then
   esac
 fi
 
-
-party_popper() {
-  for i in {1..4}; do
-      echo -ne "\r🎉 POP! 💥"
-      sleep 0.3
-      echo -ne "\r💥 POP! 🎉"
-      sleep 0.3
-  done
-  echo -e "\r🎊 Congrats! Your $PROJECT_SLUG project is ready! 🎉"
-  echo
-  echo "To get started, run:"
-  echo "cd $PROJECT_SLUG"
-  echo "tilt up"
-  echo
-}
-
-run_lambda_template_tasks() {
-  cd "$COPIER_SLUG" || exit 1
-  echo "Running AWS SAM build and validate..."
-  if ! command -v sam &>/dev/null; then
-    echo "Error: AWS SAM CLI is not installed. Please install it and try again."
-    exit 1
-  fi
-  sam build
-  sam validate --lint
-  echo "AWS Lambda template setup complete."
-}
-
-if [[ "$SCAF_CHALLENGE" == "y" ]]; then
-  start_challenge_oauthflow
-  if [[ -f "$CHALLENGE_CONFIG_PATH" ]]; then
-    start_challenge_session
-  else
-    # Force skip challenge as it cannot be started without config file
-    SCAF_CHALLENGE="n"
-  fi
-else
-  echo "Skipping challenge."
-fi
-
 echo "COPIER_OPTIONS: $COPIER_OPTIONS"
 echo "REPO_URL: $REPO_URL"
-
 
 echo "Creating your project..."
 uv run --with isort,black,copier copier copy $COPIER_OPTIONS $REPO_URL . --trust -d "is_project_slug=$COPIER_SLUG"
 
-# Check if copier was successful
-if [ $? -eq 0 ]; then
-  if [ "$TEMPLATE_CHOICE" == "1" ]; then
-    kind create cluster --name $CLUSTER_SLUG
-    cd $COPIER_SLUG
-    make compile
-    echo "Dependencies compiled successfully."
-    pwd
-    echo "Performing initial commit."
-    git add .
-    git commit -m "Initial commit"
-    party_popper
-  else
-    run_lambda_template_tasks
-  fi
-else
+# Check if copier command failed
+if [ $? -ne 0 ]; then
   echo "Failed to create project."
   exit 1
 fi
